#!/bin/bash

mkdir src/blocks;
mkdir src/blocks/$1;

for i in ${@:2}
do
    if [ $i == "css" ] || [ $i == "js" ] || [ $i == "less" ];then
        touch src/blocks/$1/$1.$i
	if [ $i == "less" ];then
		echo '/* '$1' ***********************/' >> src/blocks/$1/$1.less
		echo '.'$1' {}' >> src/blocks/$1/$1.less
		echo '@import "../blocks/'$1'/'$1'";' >> src/less/common.less
	fi
	if [ $i == "js" ];then
		echo '/* '$1' ***********************/' >> src/blocks/$1/$1.js
		echo '$(document).ready(function () {});' >> src/blocks/$1/$1.js
	fi
    fi
done